name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: armv7-unknown-linux-gnueabihf
            os: ubuntu-latest
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest

          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: arm-pc-windows-msvc
            os: windows-latest
          - target: aarch64-pc-windows-msvc
            os: windows-latest

          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest

      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - uses: actions/setup-node@v3
      with:
        node-version: 22
        cache: 'npm'

    - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y

    - run: rustup target add ${{ matrix.target }}

    - run: yarn --frozen-lockfile
    # - run: yarn build

    - run: yarn napi build --target ${{ matrix.target }} --platform

    - uses: actions/upload-artifact@v4
      with:
        name: module
        path: '*.node'
